#ifndef BLE_READINGS_H
#define BLE_READINGS_H

#include <Arduino.h>

/**
 * ==============================================================================
 * CPReady BLE Telemetry & Packet Specification
 * ==============================================================================
 * 
 * PACKET SIZE: Exactly 11 Bytes (Packed Little-Endian)
 * SERVICE UUID:        6e400001-b5a3-f393-e0a9-e50e24dcca9e
 * METRICS CHAR UUID:   6e400002-b5a3-f393-e0a9-e50e24dcca9e
 * COMMAND CHAR UUID:   6e400003-b5a3-f393-e0a9-e50e24dcca9e
 * ==============================================================================
 */

// Packet Type Identifiers (Byte 0)
constexpr uint8_t PKT_TYPE_REALTIME       = 1; // Ordinary real-time telemetry (per-stroke or 5 Hz)
constexpr uint8_t PKT_TYPE_CALIB_PROGRESS = 2; // Baseline calibration underway (hands still on chest)
constexpr uint8_t PKT_TYPE_CALIB_SUCCESS  = 3; // Baseline calibration completed (signal for app to show 'Begin Compressions')
constexpr uint8_t PKT_TYPE_FINAL_SUMMARY  = 4; // Finalized session results summary (triggers auto-save in Flutter)
constexpr uint8_t PKT_TYPE_ERROR          = 5; // Error condition (e.g. sensor failure or excessive calibration motion)

// Audio Coaching Cue Codes (Byte 7) - Generated by ESP32, Played by Phone Speaker
constexpr uint8_t PROMPT_NONE             = 0; // No audio guidance (cooldown active or target met)
constexpr uint8_t PROMPT_PUSH_HARDER      = 1; // "Push harder" (depth < 50 mm sustained >= 3.5s)
constexpr uint8_t PROMPT_PUSH_LESS        = 2; // "Push shallower" (depth > 60 mm sustained >= 3.5s)
constexpr uint8_t PROMPT_RELEASE_FULLY    = 3; // "Release chest completely" (leaning / recoil < -0.35g sustained >= 3.5s)
constexpr uint8_t PROMPT_SPEED_UP         = 4; // "Speed up" (rate < 100 cpm sustained >= 3.5s)
constexpr uint8_t PROMPT_SLOW_DOWN        = 5; // "Slow down" (rate > 120 cpm sustained >= 3.5s)
constexpr uint8_t PROMPT_GOOD_JOB         = 6; // "Good compressions" (positive praise after sustained target compliance)

// Strict 1-byte packed network packet
#pragma pack(push, 1)
struct CPRMetricsPacket {
    // Byte Offset 0: Packet Type Identifier
    uint8_t  packet_type;

    // Byte Offset 1: Recoil status (Live: 1=Full Recoil, 0=Leaning. Summary: Recoil compliance % 0..100)
    uint8_t  recoil_status;

    // Byte Offset 2..3: Cadence in compressions per minute (Live: current cpm. Summary: session mean cpm)
    uint16_t rate_cpm;

    // Byte Offset 4..5: Peak-to-peak compression depth in 0.1 mm (Live: current stroke. Summary: session mean depth)
    // Example: 540 = 54.0 mm = 5.40 cm
    uint16_t depth_tenths_mm;

    // Byte Offset 6: Cumulative Chest Compression Fraction percentage (0..100%)
    uint8_t  ccf_percent;

    // Byte Offset 7: Audio Coaching Trigger Code (0..6)
    uint8_t  audio_prompt_code;

    // Byte Offset 8: Stroke sequence index (Live) or total session compressions count (Summary)
    uint8_t  total_compressions;

    // Byte Offset 9..10: Elapsed session duration in seconds
    uint16_t session_elapsed_sec;
};
#pragma pack(pop)


/**
 * Session Summary Struct
 * Represents the final aggregated metrics across an entire completed practice session.
 */
struct CPRSessionSummary {
    float    avg_rate_cpm;
    float    avg_depth_cm;
    float    recoil_compliance_percent;
    float    final_ccf_percent;
    uint16_t total_compressions;
    uint16_t total_duration_sec;

    CPRMetricsPacket toPacket(uint8_t packetType = PKT_TYPE_FINAL_SUMMARY) const {
        CPRMetricsPacket pkt;
        pkt.packet_type        = packetType;
        pkt.recoil_status      = (uint8_t)round(recoil_compliance_percent);
        pkt.rate_cpm           = (uint16_t)round(avg_rate_cpm);
        pkt.depth_tenths_mm    = (uint16_t)round(avg_depth_cm * 100.0f); // cm to 0.1 mm
        pkt.ccf_percent        = (uint8_t)round(final_ccf_percent);
        pkt.audio_prompt_code  = PROMPT_NONE;
        pkt.total_compressions = (uint8_t)(total_compressions > 255 ? 255 : total_compressions);
        pkt.session_elapsed_sec= total_duration_sec;
        return pkt;
    }
};


/**
 * High-Level Human-Readable Reading Helper
 */
struct CPRReading {
    float    rate_cpm;
    float    depth_cm;
    bool     recoil_complete;
    float    ccf_percentage;
    uint32_t elapsed_seconds;
    uint8_t  audio_prompt_code;
    uint16_t stroke_count;

    CPRMetricsPacket toPacket(uint8_t packetType = PKT_TYPE_REALTIME) const {
        CPRMetricsPacket pkt;
        pkt.packet_type        = packetType;
        pkt.recoil_status      = recoil_complete ? 1 : 0;
        pkt.rate_cpm           = (uint16_t)round(rate_cpm);
        pkt.depth_tenths_mm    = (uint16_t)round(depth_cm * 100.0f); // cm to 0.1 mm
        pkt.ccf_percent        = (uint8_t)round(ccf_percentage);
        pkt.audio_prompt_code  = audio_prompt_code;
        pkt.total_compressions = (uint8_t)(stroke_count > 255 ? 255 : stroke_count);
        pkt.session_elapsed_sec= (uint16_t)elapsed_seconds;
        return pkt;
    }

    static CPRReading fromPacket(const CPRMetricsPacket& pkt) {
        CPRReading r;
        r.rate_cpm          = (float)pkt.rate_cpm;
        r.depth_cm          = (float)pkt.depth_tenths_mm / 100.0f;
        r.recoil_complete   = (pkt.recoil_status == 1);
        r.ccf_percentage    = (float)pkt.ccf_percent;
        r.audio_prompt_code = pkt.audio_prompt_code;
        r.stroke_count      = pkt.total_compressions;
        r.elapsed_seconds   = (uint32_t)pkt.session_elapsed_sec;
        return r;
    }

    String toDebugString() const {
        char buf[128];
        snprintf(buf, sizeof(buf),
            "Rate: %3.0f cpm | Depth: %4.2f cm | Recoil: %s | CCF: %3.0f%% | AudioCue: %d | Time: %3ds",
            rate_cpm, depth_cm, recoil_complete ? "OK" : "LEAN", ccf_percentage, audio_prompt_code, elapsed_seconds);
        return String(buf);
    }
};

/*
 ==============================================================================
 DART / FLUTTER DECODING SNIPPET (For Software & Mobile Developers)
 ==============================================================================
 
 Copy-paste this parser into your Flutter app's BLE listener:

 ```dart
 import 'dart:typed_data';

 class CPRMetrics {
   final int packetType;         // 1=Realtime, 2=Calibrating, 3=Calib Done, 4=Final Summary, 5=Error
   final bool recoilComplete;    // (Or recoil % if packetType == 4)
   final int recoilPercentage;   // 0..100%
   final int rateCpm;            // Current or average rate
   final double depthCm;         // Current or average depth (cm)
   final double depthMm;         // Current or average depth (mm)
   final int ccfPercent;         // Cumulative CCF %
   final int audioPromptCode;    // 0=None, 1=Push Harder, 2=Push Less, 3=Release Fully, 4=Speed Up, 5=Slow Down, 6=Good
   final int totalCompressions;  // Stroke count
   final int elapsedSeconds;     // Elapsed session duration

   CPRMetrics({
     required this.packetType,
     required this.recoilComplete,
     required this.recoilPercentage,
     required this.rateCpm,
     required this.depthCm,
     required this.depthMm,
     required this.ccfPercent,
     required this.audioPromptCode,
     required this.totalCompressions,
     required this.elapsedSeconds,
   });

   factory CPRMetrics.fromBytes(List<int> bytes) {
     if (bytes.length < 11) {
       throw ArgumentError("Expected 11 bytes, got ${bytes.length}");
     }
     final byteData = ByteData.sublistView(Uint8List.fromList(bytes));

     final type = byteData.getUint8(0);
     final recoilVal = byteData.getUint8(1);
     final rate = byteData.getUint16(2, Endian.little);
     final depthTenths = byteData.getUint16(4, Endian.little);
     final ccf = byteData.getUint8(6);
     final audioCue = byteData.getUint8(7);
     final totalCount = byteData.getUint8(8);
     final elapsed = byteData.getUint16(9, Endian.little);

     return CPRMetrics(
       packetType: type,
       recoilComplete: recoilVal == 1,
       recoilPercentage: recoilVal,
       rateCpm: rate,
       depthCm: depthTenths / 100.0,
       depthMm: depthTenths / 10.0,
       ccfPercent: ccf,
       audioPromptCode: audioCue,
       totalCompressions: totalCount,
       elapsedSeconds: elapsed,
     );
   }
 }

 // Characteristic UUIDs:
 // static const String serviceUuid     = "6e400001-b5a3-f393-e0a9-e50e24dcca9e";
 // static const String metricsCharUuid = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";
 // static const String commandCharUuid = "6e400003-b5a3-f393-e0a9-e50e24dcca9e";

 // Mobile Audio Cue Dispatcher Example (using flutter_tts):
 // void handleAudioPrompt(int cueCode) {
 //   switch (cueCode) {
 //     case 1: tts.speak("Push harder"); break;
 //     case 2: tts.speak("Push shallower"); break;
 //     case 3: tts.speak("Release chest completely"); break;
 //     case 4: tts.speak("Speed up"); break;
 //     case 5: tts.speak("Slow down"); break;
 //     case 6: tts.speak("Good compressions"); break;
 //   }
 // }
 ```
 ==============================================================================
*/

#endif // BLE_READINGS_H
